CREATE DATABASE SQL_DDL;
USE SQL_DDL;

CREATE TABLE MEMBER(
	id VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(5) NOT NULL,
    age INT(2),
    gender VARCHAR(2) NOT NULL,
    email VARCHAR(50), 
    promotion VARCHAR(2) DEFAULT 'x'
);

DESC MEMBER;

ALTER TABLE MEMBER MODIFY id VARCHAR(10);
ALTER TABLE MEMBER MODIFY gender VARCHAR(2) DEFAULT '여';
ALTER TABLE MEMBER ADD interest VARCHAR(100);
